### ISSUE TITLE
Do warrants that result in Preferred stock need to be "converted"?

### ISSUE THREAD

**Issue by pjohnmeyer** [captable/ocx#27]
> **⚠️ Note any Warrants implementation in OCX is dependent on the resolution of https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/pull/410**

This is the same question as #26, but for warrants.

**Comment by dbierut** [comment]
I think we do want to show accurate as-converted numbers for warrants exercisable for any series where this is known, in order to reflect the underlying shares appropriately in the Fully Diluted columns. 

In OCX v0.5, that outstanding preferred in row 11 is shown with an as-converted amount in the FD column of the Summary Snapshot; if additional Warrants down below in e.g. row 17 were exercisable for preferred, I think you would want to see that as-converted amount in the FD column as well (but because it's a warrant, you wouldn't have any shares to show in the Outstanding column here of course, and the raw unconverted warrant shares would just be a column in the Stakeholder Snapshot tab). 

![image](https://user-images.githubusercontent.com/115124853/235517895-c4a9f850-6c8d-401d-8275-f9bacf828610.png)

But like Notes for example, it is possible that certain warrants will be exercisable for a series of stock and/or a price per share still TBD, so the conversion rate or series may not be known for every warrant.

**Comment by pjohnmeyer** [comment]
@dbierut confirmed; warrant quantities on the Stakeholder Snapshot and Summary Snapshot will be "as converted".

I suspect we should do the same thing on option plans? (#26)

**Comment by JSv4** [comment]
We'd take the same approach as in #26

**Comment by pjohnmeyer** [comment]
@daviidy I think in this case we can update #31 with this info and close out this question. Agreed?
